// Autogenerated Scheme to C++ Code
// File: testCases/granborgH4.cpp
#include <iostream>
#include "Object.h"
using namespace std;

int main ()
{
	cout << Object( 1234 );
	cout << endl; 
 	cout << Object( 14.5 ); 
 	cout << endl; 
 	cout << Object( "a" ); 
 	cout << endl; 
 	cout << Object( "abc" ); 
 	cout << endl; 
 	cout << Object( "Hello World" ); 
 	cout << endl; 
 	cout << Object( "( 1 23 abc de45 )" ); 
 	cout << endl;
}
