// Autogenerated Scheme to C++ Code
// File: testCases/H4-1-10.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object reciprocal (n)
{
(	if (((n numberp ) && ((n == )!) && ))
	{
(n / )
	}
);
}
int main ()
{
(cout << (););
(cout << endl);
(cout << (()reciprocal););
(cout << endl);
(cout << (););
(cout << endl);
(cout << (););
(cout << endl);
(cout << (()reciprocal););
(cout << endl);
(cout << (););
(cout << endl);
}
