// Autogenerated Scheme to C++ Code
// File: testCases/test.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object cond_ex_1 ( Object choice,  Object value)
{
	if( choice  ==  Object( 1 )){
		return value;	}
	if( choice  ==  Object( 2 )){
		return Object( value  *  value );	}
	if( choice  ==  Object( 3 )){
		if( value  ==  Object( 0 ) ) {
			return  Object( "Division by 0 not defined" );
		}else{
			return Object( Object( 1 )  /  value );
		}	}
	return  Object( 0 );


}
Object square ( Object n)
{
	if( numberp( n ) ) {
		return Object( n  *  n );
	}else{
		return  Object( "invalid_parameter" );
	}

}
Object reciprocal ( Object n)
{
	if( numberp( n )  &&   !( n  ==  Object( 0 ) ) ) {
		return Object( Object( 1 )  /  n );
	}else{
		return  Object( "invalid_parameter" );
	}

}
Object cond_ex_2 ( Object choice,  Object value)
{
	if( choice  ==  Object( 1 )){
		return value;	}
	if( choice  ==  Object( 2 )){
		return Object( square( value ) );	}
	if( choice  ==  Object( 3 )){
		return Object( reciprocal( value ) );	}
	return  Object( 0 );


}
int main ()
{
	cout << Object( cond_ex_1( Object( 1 ) ,  Object( 5.0 ) ) );
	cout << endl; 
 	cout << Object( cond_ex_1( Object( 1 ) ,  Object( -7.0 ) ) ); 
 	cout << endl; 
 	cout << Object( cond_ex_1( Object( 2 ) ,  Object( 5.0 ) ) ); 
 	cout << endl; 
 	cout << Object( cond_ex_1( Object( 2 ) ,  Object( -7.0 ) ) ); 
 	cout << endl; 
 	cout << Object( cond_ex_1( Object( 3 ) ,  Object( 5.0 ) ) ); 
 	cout << endl; 
 	cout << Object( cond_ex_1( Object( 3 ) ,  Object( -7.0 ) ) ); 
 	cout << endl; 
 	cout << Object( cond_ex_1( Object( 3 ) ,  Object( 0 ) ) ); 
 	cout << endl; 
 	cout << Object( cond_ex_1( Object( -1 ) ,  Object( 5.0 ) ) ); 
 	cout << endl; 
 	cout << Object( cond_ex_2( Object( 1 ) ,  Object( 5.0 ) ) ); 
 	cout << endl; 
 	cout << Object( cond_ex_2( Object( 1 ) ,  Object( -7.0 ) ) ); 
 	cout << endl; 
 	cout << Object( cond_ex_2( Object( 2 ) ,  Object( 5.0 ) ) ); 
 	cout << endl; 
 	cout << Object( cond_ex_2( Object( 2 ) ,  Object( -7.0 ) ) ); 
 	cout << endl; 
 	cout << Object( cond_ex_2( Object( 3 ) ,  Object( 5.0 ) ) ); 
 	cout << endl; 
 	cout << Object( cond_ex_2( Object( 3 ) ,  Object( -7.0 ) ) ); 
 	cout << endl; 
 	cout << Object( cond_ex_2( Object( 3 ) ,  Object( 0 ) ) ); 
 	cout << endl; 
 	cout << Object( cond_ex_2( Object( -1 ) ,  Object( 5.0 ) ) ); 
 	cout << endl;
}
